name: jupyter
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - jupyterlab==3.4.5
  - nbgitpuller
  - pandas
  - geopandas
  - folium
  - altair
  - notebook
  - vega
  - pyviz::param
  - pyviz::datashader
  - pyviz::holoviews
  - pyviz::geoviews
  - pyviz::hvplot
  - bokeh::bokeh
  - pyviz::panel
  - python-snappy
  - numpy
  - beautifulsoup4
  - pip
  - pip:
      - jupyter-panel-proxy
      - qgrid
      - xlrd==1.2.0
      - ipywidgets==8.0.4
      - aiohttp_proxy
      - undetected_chromedriver
      - ipylab
      - jupyter_bokeh
